WebApplication3/Models/Hobby.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class Hobby
    {
        public string HobbyName { get; set; }
        public string StartYear { get; set; }
    }
}

WebApplication3/Models/HobbyFactory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class HobbyFactory
    {
        public static IEnumerable<Hobby> CreateHobbies()
        {
            List<Hobby> hobbies = new List<Hobby>();
            hobbies.Add(new Hobby()
            {
                HobbyName = "играть на гитаре",
                StartYear = "2009",
            });
            hobbies.Add(new Hobby()
            {
                HobbyName = "рисование (как в графичеких редакторах, так и на бумаге)",
                StartYear = "2012",
            });
            hobbies.Add(new Hobby()
            {
                HobbyName = "английский язык",
                StartYear = "2013",
            });
            return hobbies;
        }
    }
}

WebApplication3/Models/Serial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class Serial
    {
        public string Name { get; set; }
        public string About { get; set; }
        public string StartTime { get; set; }
        public string Photo { get; set; }
    }
}

WebApplication3/Models/SerialFaсtory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class SerialFaсtory
    {
        public static IEnumerable<Serial> CreateSerials()
        {
            List<Serial> serials = new List<Serial>();
            serials.Add(new Serial()
            {
                Name = "Как избежать наказания за убийство",
                About =
                    "Профессор Эннализ Китинг — блестящий адвокат. Она преподает у студентов дисциплину под названием: «Как избежать наказания за убийство». Но те даже не подозревают, что в скором времени им придется применить свои знания в этой области в реальной жизни…",
                StartTime = "С 25 сентября 2014",
                Photo = "http://cdn2.thr.com/sites/default/files/2014/09/how_to_get_away_with_murder_cast.jpg",
            });
            serials.Add(new Serial()
            {
                Name = "Ходячие мертвецы",
                About =
                    "Сериал рассказывает историю жизни семьи шерифа после того, как «зомби» — эпидемия апокалиптических масштабов захлестнула земной шар. Шериф Рик Граймс путешествует со своей семьей и небольшой группой выживших в поисках безопасного места для жизни. Но постоянный страх смерти каждый день приносит тяжелые потери, заставляя героев почувствовать глубины человеческой жестокости. Рик пытается спасти свою семью, и открывает для себя, что всепоглощающий страх тех, кто выжил, может быть опаснее бессмысленных мертвецов, бродящих по земле.",
                StartTime = "С 31 октября 2010",
                Photo = "http://cdn.playbuzz.com/cdn/e553f8b7-d9c2-45f3-b585-116e75dac4a0/b23bb893-4790-4b6e-bac9-552ad3d0a099.jpeg"
            });
            serials.Add(new Serial()
            {
                Name = "Шерлок",
                About =
                    "События разворачиваются в наши дни. Он прошел Афганистан, остался инвалидом. По возвращении в родные края встречается с загадочным, но своеобразным гениальным человеком. Тот в поиске соседа по квартире. Лондон, 2010 год. Происходят необъяснимые убийства. Скотланд-Ярд без понятия, за что хвататься. Существует лишь один человек, который в силах разрешить проблемы и найти ответы на сложные вопросы.",
                StartTime = "С 25 июля 2010",
                Photo = "http://www.planetclaire.tv/wp-content/uploads/2014/01/sherlock-sherlock-holmes-season-3.jpg"
            });
            serials.Add(new Serial()
            {
                Name = "Доктор Кто",
                About =
                    "Сериал отображает приключения мистического инопланетянина-гуманоида называющего себя Доктор, без цели путешествующего через время и пространство в космическом корабле, который снаружи выглядит как полицейская будка 60-х годов. Доктор чрезвычайно эксцентричен и имеет невероятные знания в областях технологии, истории и науки. Он путешествует вместе со своими компаньонами, попутно борясь против космических злодеев и спасая Землю от бесчисленных врагов.",
                StartTime = "С 26 марта 2005",
                Photo = "http://johnlandondesigns.com/doctor_whoniverse/images/doctors/4.jpg"
            });
            serials.Add(new Serial()
            {
                Name = "Как я встретил вашу маму",
                About =
                    "«Как я встретил вашу маму» — комедия про Теда и про то, как он влюбился. Все неприятности начинаются с того, что лучший друг Теда, Маршалл, вдруг неожиданно сообщил, что он хочет сделать предложение своей давней подруге, Лили, воспитательнице детского сада. К тому времени Тед понимает, что ему нужно прилагать больше усилий, если он действительно надеется найти свою настоящую любовь. Помогает ему в этих поисках его друг Барни, убежденный холостяк, вечно со своим, иногда чересчур, мнением на все происходящее, со склонностью к костюмам и верным способом познакомиться с девушками. Когда Тед встречает Робин, он решает, что это любовь с первого взгляда, но у судьбы в запасе есть кое-что еще.",
                StartTime = "С 19 сентября 2005",
                Photo = "http://felixbird.com/wp-content/uploads/2015/10/how_2-1024x5761-1024x576.jpg"
            });

            return serials;
        }
    }
}

WebApplication3/Controllers/ExtraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class ExtraController : Controller
    {
        // GET: Extra
        public ActionResult Serials()
        {
            var serials = SerialFaсtory.CreateSerials();
            return View(serials);
        }

        public ActionResult Biography()
        {
            return View();
        }
    }
}

WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home    
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Hobbies()
        {
            var hobbies = HobbyFactory.CreateHobbies();
            return View(hobbies);
        }
    }
}

WebApplication3/Views/Extra/Biography.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Факты</title>
    <style>
        body {
            background: #FDF6FE;
        }
    </style>
</head>
<body>
    <h1 align="center"><b><i><font color="#DC6A9E" face="Courier" size="15">Немного фактов:</font></i></b></h1>
<div>
    <ul>
        <font COLOR="#4B4B72" FACE="Courier" size="3"><i>
        <li> Я родилась 10 июня 1997 года </li>
        <li> Мой родной город - Ижевск</li>
        <li> Все 11 классов я проучилась в Гимназии №83</li>
        <li> С первого по шестой классы играла на домре, с шестого по одиннадцатый входила в состав ансамбля авторской песни "Вертикаль"</li>
        <li> В 8 классе решила уехать учиться в СПб, что успешно осуществила</li>
        <li> На данный момент учусь в СПб НИУ ИТМО</li>
        <li> Я левша :)</li>
        <li> Как ни странно, пасмурная погода невероятно поднимает мое настроение (вследствие чего Петербург - идеальный для меня город)</li>
        </i></font>
    </ul>
</div>
</body>
</html>

WebApplication3/Views/Extra/Serials.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<WebApplication3.Models.Serial> 
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Сериалы</title>
    <style>
        body {
            background: #FDF6FE;
        }
    </style>
</head>
<body>
<h1 align="center"><b><i><font color="#DC6A9E" face="Courier" size="15">Мои любимые сериалы:</font></i></b></h1>
<div>
    <ul>
        @foreach (var serial in Model)
        {
            <font COLOR="#4B4B72" FACE="Courier" size="3"><i>
                    <li>
                        <BR><b>Название сериала: @serial.Name</b>
                        <BR><b>Описание:</b> @serial.About
                        <BR><b>Начало показа:</b> @serial.StartTime
                        <BR><IMG SRC="@serial.Photo">
                    </li>
            </i></font>
        }
    </ul>
</div>
</body>
</html>

WebApplication3/Views/Home/Hobbies.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<WebApplication3.Models.Hobby> 
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Хобби</title>
    <style>
        body {
            background: #FDF6FE;
        }
    </style>
</head>
<body>
<h1 align="center"><b><i><font color="#DC6A9E" face="Courier" size="15">Мои хобби</font></i></b></h1>
        <div>
            <ul>
                @foreach (var hobby in Model)
                {
                    <li>
                        <font COLOR="#4B4B72" FACE="Courier" size="3"><i>Я люблю @hobby.HobbyName.
                        Я начала увлекаться этим в @hobby.StartYear г. </i></font>
                    </li>
                }
            </ul>
        </div>
</body>
</html>

WebApplication3/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Домашняя страница</title>
    <style>
        body {
            background:#FDF6FE;
        }
    </style>
</head>
<body link="#BC60D2" ALINK="#45CBD9" VLINK="#2D557C">
<h1 align="center"><b><i><font color="#DC6A9E" face ="Courier" size ="20">Сайт Семакиной Ольги</font></i></b></h1>
    <div>
        <p align="center">
            <font COLOR="#53BCEE" FACE="Courier" size="5">
                <i><b>
                 На данном сайте хранится некая информация обо мне, выберите один из пунктов ниже для её прочтения:
                 </b></i>
            </font>
        </p>
        <font COLOR="#53BCEE" FACE="Courier" size="5"><i>
            <ul>
                <li> @Html.ActionLink("Мои хобби", "Hobbies", "Home")</li>
                <li> @Html.ActionLink("Мои любимые сериалы", "Serials", "Extra")</li>
                <li> @Html.ActionLink("Немного информации обо мне", "Biography", "Extra")</li>
            </ul>
        </i></font>
    </div>
</body>
</html>

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body> 
    <ul>
        <font COLOR="#53BCEE" FACE="Courier" size="5"><i>
            <li> @Html.ActionLink("Домашняя страница", "Index", "Home")</li>
        </i></font>
    </ul>
        <div>
            @RenderBody()
        </div>
</body>
</html>